server:
  port: 9000
  servlet:
    context-path:
  tomcat:
    uri-encoding: UTF-8
    basedir: /home/nbiot
    accesslog:
      pattern: common
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      request-attributes-enabled: true
      rename-on-rotate: true
    max-http-form-post-size: 200MB
  jetty:
    max-http-form-post-size: 20000000B
logging:
  level:
    root: INFO
    #    org.flowable: DEBUG
    com.jeeplus: INFO
    com.wxxx: INFO
    org.apache.shiro.cache.ehcache.EhCacheManager: WARN
spring:
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
  devtools:
    restart:
      enabled: true

  #  jpa:
  #    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
